### PR TITLE
Use prop-types package

### PR DESCRIPTION
**Pull request by SteamRiC**
`React.propTypes` is deprecated in version 15.5 and this causes warnings
when using react-intl-tel-input.

### CODE REVIEW

**Comment by ostap0207** [comment]
bump the version?

**Comment by SteamRiC** [comment]
https://github.com/salemove/react-intl-tel-input/pull/2

**Comment by SteamRiC** [comment]
!merge

**Comment by willmore** [comment]
!check

**Comment by deiwin** [comment]
!check

**Pull request merged**
